// src/App.tsx
import Booth from './components/Booth';

function App() {
  const votes = [
    {
      option: 'Sim',
      count: 16,
    },
    {
      option: 'Não',
      count: 12,
    },
  ];
  const options = votes.map(vote => vote.option);

  function handleVote(option: string) {
    console.log(option);
  }

  return <Booth options={options} onVote={handleVote} />;
}

export default App;

// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: '<booth [options]="options" (vote)="onVote($event)"></booth>',
})
export class AppComponent {
  votes = [
    {
      option: 'Sim',
      count: 8,
    },
    {
      option: 'Não',
      count: 12,
    },
  ];

  get options() {
    return this.votes.map((vote) => vote.option);
  }

  onVote(option: string) {
    console.log(option);
  }
}
