// src/app/booth.component.ts
import { Component, EventEmitter, Output } from '@angular/core';

import { VotingService } from './voting.service';

@Component({
  selector: 'booth',
  template: `
    <button
      type="button"
      *ngFor="let option of options; index as i"
      [ngClass]="[
        'transition-all bg-gray-800 hover:bg-gray-900 text-gray-200 rounded p-2',
        i > 0 ? 'ml-3' : ''
      ]"
      (click)="vote.emit(option)"
    >
      {{ option }}
    </button>
  `,
})
export class BoothComponent {
  @Output() vote = new EventEmitter<string>();

  constructor(private votingService: VotingService) {}

  get options() {
    return this.votingService.votes.map((vote) => vote.option);
  }
}

// src/components/Booth.vue
<template>
  <button
    v-for="(option, index) in options"
    :key="option"
    type="button"
    class="
      transition-all
      bg-gray-800
      hover:bg-gray-900
      text-gray-200
      rounded
      p-2
    "
    :class="index > 0 && 'ml-3'"
    @click="$emit('vote', option)"
  >
    {{ option }}
  </button>
</template>

<script lang="ts">
import { computed, defineComponent } from 'vue';

import useVoting from '../store/voting';

export default defineComponent({
  name: 'Booth',
  emits: ['vote'],
  setup() {
    const voting = useVoting();

    const options = computed(() => voting.votes.map(vote => vote.option));

    return {
      options,
    };
  },
});
</script>
