// src/Booth.svelte
<script>
  export let options;
  export let onVote;
</script>

{#each options as option, index}
  <button
    type="button"
    class={`transition-all bg-gray-800 hover:bg-gray-900 text-gray-200 rounded p-2 ${
      index > 0 ? 'ml-3' : ''
    }`}
    on:click={onVote(option)}
  >
    {option}
  </button>
{/each}

// src/components/Booth.tsx
import cx from 'classnames';

type BoothProps = {
  options: string[];
  onVote?: (option: string) => void;
};

export default function Booth({ options, onVote = () => {} }: BoothProps) {
  return (
    <>
      {options.map((option, index) => (
        <button
          key={option}
          type="button"
          className={cx(
            'transition-all',
            'bg-gray-800',
            'hover:bg-gray-900',
            'text-gray-200',
            'rounded',
            'p-2',
            { 'ml-3': index > 0 }
          )}
          onClick={() => onVote(option)}
        >
          {option}
        </button>
      ))}
    </>
  );
}
