// src/components/Result.tsx
import { Vote } from 'types/Vote';

type ResultProps = {
  votes: Vote[];
};

export default function Result({ votes }: ResultProps) {
  const totalVotes = votes.reduce(
    (totalVotes, vote) => totalVotes + vote.count,
    0
  );
  const orderedVotes = [...votes].sort((a, b) => b.count - a.count);
  const parsedVotes = orderedVotes.map(vote => ({
    ...vote,
    rate: Math.round((vote.count * 100) / totalVotes),
  }));

  return (
    <ol className="list-decimal text-gray-200">
      {parsedVotes.map(vote => (
        <li key={vote.option}>
          {vote.option} - {vote.count} votos ({vote.rate}%)
        </li>
      ))}
    </ol>
  );
}

// src/components/Result.vue
<template>
  <ol class="list-decimal text-gray-200">
    <li v-for="vote in parsedVotes" :key="vote.option">
      {{ vote.option }} - {{ vote.count }} votos ({{ vote.rate }}%)
    </li>
  </ol>
</template>

<script lang="ts">
import { computed, defineComponent, PropType, ref } from 'vue';

import { Vote } from '@/types/Vote';

export default defineComponent({
  name: 'Result',
  props: {
    votes: {
      type: Array as PropType<Vote[]>,
      required: true,
    },
  },
  setup(props) {
    const votes = ref(props.votes);
    const totalVotes = computed(() =>
      votes.value.reduce((totalVotes, vote) => totalVotes + vote.count, 0)
    );

    const orderedVotes = computed(() =>
      [...votes.value].sort((a, b) => b.count - a.count)
    );
    const parsedVotes = computed(() =>
      orderedVotes.value.map(vote => ({
        ...vote,
        rate: Math.round((vote.count * 100) / totalVotes.value),
      }))
    );

    return {
      parsedVotes,
    };
  },
});
</script>
