// src/Result.svelte
<script>
  export let votes;
  export let className = '';

  $: totalVotes = votes.reduce(
    (totalVotes, vote) => totalVotes + vote.count,
    0
  );

  $: parsedVotes = [...votes]
    .sort((a, b) => b.count - a.count)
    .map(vote => ({
      ...vote,
      rate: Math.round((vote.count * 100) / totalVotes),
    }));
</script>

<ol class={`list-decimal text-gray-200 ${className}`}>
  {#each parsedVotes as vote}
    <li>
      {vote.option} - {vote.count} votos ({vote.rate}%)
    </li>
  {/each}
</ol>

// src/components/Result.tsx
import { Vote } from 'types/Vote';

type ResultProps = {
  votes: Vote[];
};

export default function Result({ votes }: ResultProps) {
  const totalVotes = votes.reduce(
    (totalVotes, vote) => totalVotes + vote.count,
    0
  );
  const orderedVotes = [...votes].sort((a, b) => b.count - a.count);
  const parsedVotes = orderedVotes.map(vote => ({
    ...vote,
    rate: Math.round((vote.count * 100) / totalVotes),
  }));

  return (
    <ol className="list-decimal text-gray-200">
      {parsedVotes.map(vote => (
        <li key={vote.option}>
          {vote.option} - {vote.count} votos ({vote.rate}%)
        </li>
      ))}
    </ol>
  );
}
