// src/components/VotingCard.vue
<template>
  <div class="bg-gray-600 max-w-max p-6 flex flex-col rounded">
    <h1 class="font-bold text-2xl mb-4 text-gray-100">{{ title }}</h1>

    <div class="flex justify-center">
      <Booth
        v-if="votingState === 'open'"
        :options="options"
        @vote="handleVote"
      />
      <Result v-if="votingState === 'closed'" :votes="boothVotes" />
    </div>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent, PropType, ref, watch } from 'vue';

import { Vote } from '@/types/Vote';

import Booth from './Booth.vue';
import Result from './Result.vue';

type VotingStates = 'open' | 'closed';

export default defineComponent({
  name: 'VotingCard',
  components: {
    Booth,
    Result,
  },
  props: {
    votes: {
      type: Array as PropType<Vote[]>,
      required: true,
    },
    title: {
      type: String,
      required: true,
    },
    state: {
      type: String,
      default: 'open',
    },
  },
  setup(props) {
    const boothVotes = ref(props.votes);
    const options = computed(() => boothVotes.value.map(vote => vote.option));
    const votingState = ref<VotingStates>(props.state as VotingStates);

    watch(props, () => {
      votingState.value = props.state as VotingStates;
    });

    function incrementCountOn(option: string) {
      const vote = boothVotes.value.find(vote => vote.option === option);

      if (!vote) {
        return;
      }

      vote.count += 1;
    }

    function handleVote(option: string) {
      votingState.value = 'closed';
      incrementCountOn(option);
    }

    return {
      votingState,
      options,
      handleVote,
      boothVotes,
    };
  },
});
</script>

// src/components/VotingCard.tsx
import * as React from 'react';

import { Vote } from 'types/Vote';

import Booth from './Booth';
import Result from './Result';

type VotingStates = 'open' | 'closed';

type VotingCardProps = {
  votes: Vote[];
  title: string;
  state?: VotingStates;
};

export default function VotingCard({
  title,
  votes,
  state = 'open',
}: VotingCardProps) {
  const [boothVotes, setBoothVotes] = React.useState(votes);
  const [votingState, setVotingState] = React.useState(state);

  const options = React.useMemo(() => boothVotes.map(vote => vote.option), [
    boothVotes,
  ]);

  function incrementCountOn(option: string) {
    setBoothVotes(oldVotes =>
      oldVotes.map(vote => ({
        ...vote,
        count: vote.option === option ? vote.count + 1 : vote.count,
      }))
    );
  }

  function handleVote(option: string) {
    setVotingState('closed');
    incrementCountOn(option);
  }

  return (
    <div className="bg-gray-600 max-w-max p-6 flex flex-col rounded">
      <h1 className="font-bold text-2xl mb-4 text-gray-100">{title}</h1>

      <div className="flex justify-center">
        {votingState === 'open' && (
          <Booth options={options} onVote={handleVote} />
        )}
        {votingState === 'closed' && <Result votes={boothVotes} />}
      </div>
    </div>
  );
}
