// src/App.tsx
import Booth from './components/Booth';

function App() {
  const votes = [
    {
      option: 'Sim',
      count: 16,
    },
    {
      option: 'Não',
      count: 12,
    },
  ];
  const options = votes.map(vote => vote.option);

  function handleVote(option: string) {
    console.log(option);
  }

  return <Booth options={options} onVote={handleVote} />;
}

export default App;

// src/App.vue
<template>
  <Booth :options="options" @vote="handleVote" />
</template>

<script lang="ts">
import { computed, defineComponent, ref } from 'vue';

import Booth from './components/Booth.vue';

export default defineComponent({
  name: 'App',
  components: {
    Booth,
  },
  setup() {
    const votes = ref([
      {
        option: 'Sim',
        count: 8,
      },
      {
        option: 'Não',
        count: 12,
      },
    ]);
    const options = computed(() => votes.value.map(vote => vote.option));

    function handleVote(option: string) {
      console.log(option);
    }

    return {
      votes,
      options,
      handleVote,
    };
  },
});
</script>
