// src/components/VotingCard.tsx
import * as React from 'react';

import { Vote } from 'types/Vote';

import Booth from './Booth';
import Result from './Result';

type VotingStates = 'open' | 'closed';

type VotingCardProps = {
  votes: Vote[];
  title: string;
  state?: VotingStates;
};

export default function VotingCard({
  title,
  votes,
  state = 'open',
}: VotingCardProps) {
  const [boothVotes, setBoothVotes] = React.useState(votes);
  const [votingState, setVotingState] = React.useState(state);

  const options = React.useMemo(() => boothVotes.map(vote => vote.option), [
    boothVotes,
  ]);

  function incrementCountOn(option: string) {
    setBoothVotes(oldVotes =>
      oldVotes.map(vote => ({
        ...vote,
        count: vote.option === option ? vote.count + 1 : vote.count,
      }))
    );
  }

  function handleVote(option: string) {
    setVotingState('closed');
    incrementCountOn(option);
  }

  return (
    <div className="bg-gray-600 max-w-max p-6 flex flex-col rounded">
      <h1 className="font-bold text-2xl mb-4 text-gray-100">{title}</h1>

      <div className="flex justify-center">
        {votingState === 'open' && (
          <Booth options={options} onVote={handleVote} />
        )}
        {votingState === 'closed' && <Result votes={boothVotes} />}
      </div>
    </div>
  );
}

// src/VotingCard.svelte
<script>
  import Booth from './Booth.svelte';
  import Result from './Result.svelte';

  export let title;
  export let votes;
  export let state = 'open';

  $: options = votes.map(vote => vote.option);

  function incrementCountOn(option) {
    votes = votes.map(vote => ({
      ...vote,
      count: vote.option === option ? vote.count + 1 : vote.count,
    }));
  }

  function handleVote(option) {
    state = 'closed';
    incrementCountOn(option);
  }
</script>

<div class="bg-gray-600 max-w-max p-6 flex flex-col rounded">
  <h1 class="font-bold text-2xl mb-4 text-gray-100">{title}</h1>

  <div class="flex justify-center">
    {#if state === 'open'}
      <Booth {options} onVote={handleVote} />
    {/if}

    {#if state === 'closed'}
      <Result {votes} />
    {/if}
  </div>
</div>
